### ISSUE TITLE
Complete DApp section in the next two weeks.

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#400]

**Comment by owocki** [comment]
[right now this module seems to only feature tools and architecture](https://github.com/ethereumbook/ethereumbook/blob/develop/dapps.asciidoc)  do ya'll have any interest in featuring some *live* dapps in the content?

**Comment by aantonop** [comment]
What do you suggest?

**Comment by owocki** [comment]
if i had my druthers, keep the 

# What is a DApp?

# Components of a DApp

# DApp Frameworks

sections, and then add 

# Live Dapps

## Infrastructure

ETH-pm, ENS, Eth Alarm Clock

## DEXes (Decentralized Exchanges)

Radar Relay, ForkDelta,

## CryptoCollectables

CryptoKitties, 

## Knowledge Work 

ETHlance, Gitcoin, Bounty0x

## Other

Decentraland

**Comment by aantonop** [comment]
@owocki: Suggestion is great. Can you do a quick PR to add those sections to the outline?

**Comment by chanan-sack** [comment]
done, added live Dapps by name but without the different sections because it didn't match the layout of the asciidoc

**Comment by owocki** [comment]
Thanks for doing this @chanan-sack !  

https://github.com/ethereumbook/ethereumbook/commit/dbc0226971f73330755f2a474e7f77236ec8c099

**Comment by SylTi** [comment]
You forgot some of the major DEX like : 
- 0x (https://0xproject.com/) 
- Kyber (https://kyber.network/)
- Bancor (https://www.bancor.network/

**Comment by chanan-sack** [comment]
I dont think those are important to be added, i purposely put one there thinking it's fairly simple and promising, DEX'S are a complex issue and in my opinion we shouldn't make it a focused catagory

**Comment by danieljwonder** [comment]
It would probably be useful to reference [State of The DAPPS](https://www.stateofthedapps.com/). It is the largest compilation DAPPs in a single place that I'm aware of and would allow the reader to perform their own continued research.

**Comment by SylTi** [comment]
I agree, didn't know it existed, thanks for sharing!

**Comment by manilabay** [comment]
I visited last week stateofthedapps and totally agree it deserves a link in the references in this dapps section

**Comment by ltfschoen** [comment]
ConsenSys's Truffle Boxes should also have a mention since they provide boilerplate DApps for others to build upon http://truffleframework.com/boxes/

**Comment by emmonspired** [comment]
If it helps, I have a full working example of a Dapp with Truffle Boxes & Angular, as well as a Whitepaper explanation of what it does. https://github.com/emmonspired/erc20-digital-signature-verify

Whitepaper and Demo: UX for Authenticated & Verified ERC20 Payments Using MetaMask and EthSigUtil https://steemit.com/ethereum/@emmonspired/whitepaper-and-demo-ux-for-authenticated-and-verified-erc20-payments-using-metamask-and-ethsigutil
